version: '2'

services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www:cached
    ports:
      - 80:80
    links:
      - app
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www:cached
    depends_on:
      - laravel-db

  laravel-db:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"

    